# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles.
# SupportedStyles: either, start_of_block, start_of_line
Lint/BlockAlignment:
  Include:
    - 'spec/rakuten_web_service/genre_information_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
# SupportedStyles: keyword, variable, start_of_line
Lint/EndAlignment:
  Exclude:
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/rakuten_web_service/genre.rb'
    - 'lib/rakuten_web_service/resource.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'spec/rakuten_web_service/books/total_spec.rb'

# Offense count: 3
Metrics/AbcSize:
  Max: 21

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 186
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 150

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 17

# Offense count: 1
# Cop supports --auto-correct.
Performance/RedundantBlockCall:
  Exclude:
    - 'lib/rakuten_web_service/configuration.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: MaxKeyValuePairs.
Performance/RedundantMerge:
  Exclude:
    - 'lib/rakuten_web_service/genre.rb'

# Offense count: 2
Style/AccessorMethodName:
  Exclude:
    - 'lib/rakuten_web_service/resource.rb'

# Offense count: 39
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Style/AlignHash:
  Exclude:
    - 'lib/rakuten_web_service/ichiba/item.rb'
    - 'spec/rakuten_web_service/books/genre_spec.rb'
    - 'spec/rakuten_web_service/client_spec.rb'
    - 'spec/rakuten_web_service/gora/course_detail_spec.rb'
    - 'spec/rakuten_web_service/gora/course_spec.rb'
    - 'spec/rakuten_web_service/gora/plan_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'

# Offense count: 40
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Style/AlignParameters:
  Exclude:
    - 'lib/rakuten_web_service/ichiba/item.rb'
    - 'lib/rakuten_web_service/ichiba/product.rb'
    - 'lib/rakuten_web_service/kobo/ebook.rb'
    - 'lib/rakuten_web_service/recipe.rb'
    - 'spec/rakuten_web_service/client_spec.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'examples/gora_search.rb'
    - 'spec/rakuten_web_service/configuration_spec.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Exclude:
    - 'lib/rakuten_web_service/gora/course_detail.rb'
    - 'lib/rakuten_web_service/ichiba/item.rb'

# Offense count: 2
Style/CaseEquality:
  Exclude:
    - 'lib/rakuten_web_service/client.rb'
    - 'lib/rakuten_web_service/recipe/category.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep, IndentationWidth.
# SupportedStyles: case, end
Style/CaseIndentation:
  Exclude:
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 39
Style/Documentation:
  Enabled: false

# Offense count: 77
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: leading, trailing
Style/DotPosition:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/EachWithObject:
  Exclude:
    - 'lib/rakuten_web_service/configuration.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty, nil, both
Style/EmptyElse:
  Exclude:
    - 'lib/rakuten_web_service/recipe/category.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'spec/rakuten_web_service/books/book_spec.rb'

# Offense count: 7
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'lib/rakuten_web_service/books/resource.rb'
    - 'lib/rakuten_web_service/client.rb'
    - 'lib/rakuten_web_service/configuration.rb'
    - 'lib/rakuten_web_service/recipe/category.rb'
    - 'lib/rakuten_web_service/resource.rb'
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/rakuten_web_service/client_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'
    - 'spec/rakuten_web_service/ichiba/ranking_spec.rb'
    - 'spec/rakuten_web_service/recipe/category_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines
Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'lib/rakuten_web_service/recipe/category.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Exclude:
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Style/ExtraSpacing:
  Exclude:
    - 'lib/rakuten_web_service/ichiba/item.rb'

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/rakuten_web_service/client.rb'
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'Rakefile'

# Offense count: 26
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Style/IndentHash:
  Exclude:
    - 'lib/rakuten_web_service/ichiba/item.rb'
    - 'spec/rakuten_web_service/books/genre_spec.rb'
    - 'spec/rakuten_web_service/gora/course_detail_spec.rb'
    - 'spec/rakuten_web_service/gora/course_spec.rb'
    - 'spec/rakuten_web_service/gora/plan_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: normal, rails
Style/IndentationConsistency:
  Exclude:
    - 'lib/rakuten_web_service/recipe/category.rb'
    - 'lib/rakuten_web_service/resource.rb'
    - 'spec/rakuten_web_service/genre_information_spec.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'lib/rakuten_web_service/search_result.rb'
    - 'spec/rakuten_web_service/genre_information_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Exclude:
    - 'spec/rakuten_web_service/genre_information_spec.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: symmetrical, new_line, same_line
Style/MultilineHashBraceLayout:
  Exclude:
    - 'spec/rakuten_web_service/client_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'

# Offense count: 138
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented, indented_relative_to_receiver
Style/MultilineMethodCallIndentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'lib/rakuten_web_service/resource.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/Not:
  Exclude:
    - 'lib/rakuten_web_service/response.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 7

# Offense count: 1
Style/OpMethod:
  Exclude:
    - 'lib/rakuten_web_service/resource.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'lib/rakuten_web_service/response.rb'
    - 'rakuten_web_service.gemspec'

# Offense count: 12
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Exclude:
    - 'lib/rakuten_web_service/configuration.rb'
    - 'lib/rakuten_web_service/resource.rb'
    - 'lib/rakuten_web_service/response.rb'
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 3
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/rakuten_web_service/configuration.rb'
    - 'lib/rakuten_web_service/response.rb'
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: short, verbose
Style/PreferredHashMethods:
  Exclude:
    - 'lib/rakuten_web_service/configuration.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantParentheses:
  Exclude:
    - 'lib/rakuten_web_service/response.rb'
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'lib/rakuten_web_service/configuration.rb'

# Offense count: 29
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'lib/rakuten_web_service/books/genre.rb'
    - 'lib/rakuten_web_service/books/resource.rb'
    - 'lib/rakuten_web_service/configuration.rb'
    - 'lib/rakuten_web_service/genre.rb'
    - 'lib/rakuten_web_service/gora/course.rb'
    - 'lib/rakuten_web_service/gora/course_detail.rb'
    - 'lib/rakuten_web_service/gora/plan.rb'
    - 'lib/rakuten_web_service/ichiba/genre.rb'
    - 'lib/rakuten_web_service/ichiba/item.rb'
    - 'lib/rakuten_web_service/ichiba/product.rb'
    - 'lib/rakuten_web_service/ichiba/shop.rb'
    - 'lib/rakuten_web_service/kobo/ebook.rb'
    - 'lib/rakuten_web_service/kobo/genre.rb'
    - 'lib/rakuten_web_service/recipe.rb'
    - 'lib/rakuten_web_service/resource.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RescueEnsureAlignment:
  Exclude:
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Exclude:
    - 'lib/rakuten_web_service/gora/plan.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: space, no_space
Style/SpaceAroundEqualsInParameterDefault:
  Exclude:
    - 'lib/rakuten_web_service/books/genre.rb'
    - 'lib/rakuten_web_service/genre.rb'
    - 'lib/rakuten_web_service/ichiba/genre.rb'
    - 'lib/rakuten_web_service/ichiba/item.rb'
    - 'lib/rakuten_web_service/ichiba/shop.rb'
    - 'lib/rakuten_web_service/kobo/genre.rb'
    - 'lib/rakuten_web_service/resource.rb'
    - 'lib/rakuten_web_service/search_result.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Exclude:
    - 'lib/rakuten_web_service/gora/course_detail.rb'
    - 'lib/rakuten_web_service/gora/plan.rb'

# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Exclude:
    - 'spec/rakuten_web_service/books/book_spec.rb'
    - 'spec/rakuten_web_service/books/cd_spec.rb'
    - 'spec/rakuten_web_service/books/dvd_spec.rb'
    - 'spec/rakuten_web_service/books/foreign_book_spec.rb'
    - 'spec/rakuten_web_service/books/game_spec.rb'
    - 'spec/rakuten_web_service/books/magazine_spec.rb'
    - 'spec/rakuten_web_service/books/software_spec.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space, compact
Style/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'lib/rakuten_web_service/gora/course_detail.rb'
    - 'spec/rakuten_web_service/client_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'
    - 'spec/rakuten_web_service/ichiba/item_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Exclude:
    - 'lib/rakuten_web_service/ichiba/item.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Exclude:
    - 'rakuten_web_service.gemspec'

# Offense count: 116
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'lib/rakuten_web_service/configuration.rb'
    - 'lib/rakuten_web_service/version.rb'
    - 'rakuten_web_service.gemspec'
    - 'spec/rakuten_web_service/books/book_spec.rb'
    - 'spec/rakuten_web_service/client_spec.rb'
    - 'spec/rakuten_web_service/configuration_spec.rb'
    - 'spec/rakuten_web_service/genre_information_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'
    - 'spec/rakuten_web_service/ichiba/item_spec.rb'
    - 'spec/rakuten_web_service/kobo/ebook_spec.rb'
    - 'spec/rakuten_web_service/recipe/category_spec.rb'
    - 'spec/spec_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'spec/rakuten_web_service/gora/course_spec.rb'
    - 'spec/rakuten_web_service/ichiba/item_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
# SupportedStyles: comma, consistent_comma, no_comma
Style/TrailingCommaInLiteral:
  Exclude:
    - 'spec/rakuten_web_service/gora/plan_spec.rb'

# Offense count: 11
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Exclude:
    - 'lib/rakuten_web_service/books/cd.rb'
    - 'lib/rakuten_web_service/books/dvd.rb'
    - 'lib/rakuten_web_service/books/foreign_book.rb'
    - 'lib/rakuten_web_service/books/magazine.rb'
    - 'lib/rakuten_web_service/books/resource.rb'
    - 'lib/rakuten_web_service/configuration.rb'
    - 'lib/rakuten_web_service/ichiba/item.rb'
    - 'lib/rakuten_web_service/search_result.rb'
    - 'spec/rakuten_web_service/genre_information_spec.rb'
    - 'spec/rakuten_web_service/ichiba/genre_spec.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, IgnoreClassMethods, Whitelist.
# Whitelist: to_ary, to_a, to_c, to_enum, to_h, to_hash, to_i, to_int, to_io, to_open, to_path, to_proc, to_r, to_regexp, to_str, to_s, to_sym
Style/TrivialAccessors:
  Exclude:
    - 'lib/rakuten_web_service/resource.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Exclude:
    - 'rakuten_web_service.gemspec'
