module RakutenWebService
  module Ichiba
    class Genre < RakutenWebService::BaseGenre
      def ranking: (?::Hash[untyped, untyped] options) -> untyped

      def products: (?::Hash[untyped, untyped] options) -> untyped
    end
  end
end
